# This is a basic workflow to help you get started with Actions

name: Release notification to Google Chat room

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    branches: [ master ]
    types: [ published ]

jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chat.googleapis.com/v1/spaces/AAAAKKUxGFw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=GwXy1u8hxGbTdusa1iF9rfI7gsAvnXuUKZCCVFf8Dnc%3D'
          method: 'POST'
          data: '{"cards":[{"header":{"title":"${{ github.repository }} - Nueva release","subtitle":"${{ github.event.release.author.login }}","imageUrl":"https://github.com/fluidicon.png","imageStyle":"IMAGE"},"sections":[{"widgets":[{"keyValue":{"topLabel":"Versión","content":"${{ github.event.release.name }} (${{ github.event.release.tag_name }})"}},{"keyValue":{"topLabel":"Autor","content":"${{ github.event.release.author.login }}"}},{"textParagraph":{"text":"${{ github.event.release.body }}"}},{"buttons":[{"textButton":{"text": "Abrir en GitHub","onClick":{"openLink":{"url":"${{ github.event.release.html_url }}"}}}}]}]}]}]}'
