# This is a basic workflow to help you get started with Actions

name: Release notification to Google Chat room

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    branches: [ master ]
    types: [ published ]

jobs:
  notify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://chat.googleapis.com/v1/spaces/AAAAKKUxGFw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=GwXy1u8hxGbTdusa1iF9rfI7gsAvnXuUKZCCVFf8Dnc%3D'
          method: 'POST'
          data: '{"text": "${{ github.repository }} - Nueva release publicada: "${{ github.event.release.name }}" (${{ github.event.release.tag_name }}) por "}'
